---
title: "Base Ranker: Proportional Reporting Ratio (PRR)"
author:
  - name: Nan Xiao
    url: https://nanx.me/
    affiliation: Seven Bridges
    affiliation_url: https://www.sevenbridges.com/
  - name: Soner Koc
    url: https://github.com/skoc
    affiliation: Seven Bridges
    affiliation_url: https://www.sevenbridges.com/
  - name: Kaushik Ghose
    url: https://kaushikghose.wordpress.com/
    affiliation: Seven Bridges
    affiliation_url: https://www.sevenbridges.com/
date: "`r Sys.Date()`"
output: distill::distill_article
bibliography: rankv.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, cache = TRUE)
```

Load the packages for PRR-based singal detection and ranking:

```{r}
suppressMessages(library("PhViD"))
library("kableExtra")
```

Load the preprocessed VAERS data and transform it into the analyzable format:

```{r}
df_p <- readRDS("data-processed/df_p.rds")
df_p <- df_p[, 1:3]
df_v <- as.PhViD(df_p, MARGIN.THRES = 10)
```

Calculate the Proportional Reporting Ratio (PRR) [@evans2001] and the ranking statistic --- lower bound of the 95% two-sided confidence interval of log(PRR):

```{r}
lst_prr <- PRR(df_v, MIN.n11 = 10, DECISION = 3, RANKSTAT = 2)
df_prr <- lst_prr$SIGNALS[order(lst_prr$SIGNALS$"LB95(log(PRR))", decreasing = TRUE), 1:8]
row.names(df_prr) <- NULL
```

View the top ranked vaccine-adverse event pairs:

```{r}
head(df_prr) %>% kable() %>% kable_styling()
```

```{r,echo=FALSE}
saveRDS(df_prr, file = "data-processed/df_prr.rds")
```
